server:
  port: 8401

spring:
  application:
    name: Sentinel-Service

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #Nacos服务注册中心地址

    sentinel:
      transport:
        port: 8719 #sentinel客户端 与 sentinel服务端 的传输端口
        dashboard: localhost:8080 #配置Sentinel dashboard地址，通过web浏览器访问该地址可以进入控制台

management:
  endpoints:
    web:
      exposure:
        include: "*"

feign:
  sentinel:
    enabled: true # 激活Sentinel对Feign的支持

